spring-webflux:
  database:
    host: 127.0.0.1
    port: 5452
    schema: public
    user: edurmus
    password: pwdedurmus
    name: webflux
    pool:
      size:
        initial: 3
        max: 10

spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5452/webflux
    user: ${spring-webflux.database.user}
    password: ${spring-webflux.database.password}
    baseline-version: 0

server:
  port: 8081